name = "easeprobe-worker"
main = "dist/worker.js"
compatibility_date = "2023-10-02"

[[rules]]
type = "CompiledWasm"
globs = ["*.wasm"]
fallthrough = false

[vars]
CONFIG_YAML = """
{
  "http": [
    {
      "name": "Google",
      "url": "https://www.google.com",
      "interval": "1m",
      "timeout": "5s"
    }
  ],
  "tcp": [
    {
      "name": "xray-reality-jp",
      "host": "154.19.186.11:20080",
      "interval": "60s"
    }
  ]
}
"""

[triggers]
crons = ["* * * * *"]
